---
- hosts: all
  roles:
  - role: common
  - role: darwin
    when: ansible_os_family == 'Darwin'
    homebrew_taps:
    - homebrew/completions
    homebrew_packages:
    - wget
    - httpie
    - bro
    - byobu
    - dos2unix
    - exif
    - aide
    - aircrack-ng
    - airspy
    - amap
    - apib
    - azure-cli
    - argus
    - argus-clients
    - arp-scan
    - arp-sk
    - arping
    - arpoison
    - ascii
    - asciinema2gif
    - atlassian-cli
    - autobench
    - autojump
    - autopsy
    - awslogs
    - bandcamp-dl
    - base64
    - bind
    - bittwist
    - blucat
    - bmon
    - ccat
    - snort
    - pulledpork
    - lcrack
    - ncrack
    - cracklib
    - pkcrack
    - fcrackzip
    - ophcrack
    - pdfcrack
    - truecrack
    - hydra
    - john
    - sshtrix
    - john-jumbo
    - nmap
    - ndiff
    - ngrep
    - sngrep
    - tcptrace
    - tcptraceroute
    - libdnet
    - tcpreplay
    - openssl
    - boost
    - tcpflow
    - ipcalc
    - sipcalc
    - ipsumdump
    - p0f
    - libevent
    - libnet
    - fragroute
    - masscan
    - netcat
    - netcat6
    - socat
    - freetype
    - jpeg
    - yara
    - volatility
    - suricata
    - ipv6toolkit
    - clog
    - grc
    - httpry
    - ettercap
    homebrew_cask_packages:
    - vmware-fusion
    - dropbox
    - firefox
    - google-chrome
    - gpgtools
    - skype
    - teamviewer
    - zoc
    - Textmate
    - devonthink-pro 
    - freemind
    - gns3
    - google-earth
    - securid
    - unetbootin
    - VirtualBox
    - wireshark
    - vagrant
    - google-drive
    - burp-suite
    mas_packages:
    - name: 1Password
      id: 443987910
    - name: Microsoft Remote Desktop
      id: 715768417
